### ISSUE TITLE
Indexer in Sandbox is Broken due to New Requirement of Follower Node

### ISSUE THREAD

**Issue by tzaffi** [algorand/sandbox#175]
### Add a Follower Node to Sandbox

This is a skeleton of an issue which hopefully will be resolved soon.

## Q: I’ll be adding another node - a follower - and then have it serve only to indexer ?

Yes, exactly.

## Q: Is the `algod` broken too?

No, it's perfectly fine, just doesn't work for the indexer as currently configured

## TODO

- [ ] Add the follower to the same algod container
  - [ ] it should serve on a new port `4003` ???
  - [ ] indexer should read from that port
- [ ] (Optional) measure the memory / cpu / time requirements of sandbox algod container
  - [ ] as currently configured
  - [ ] with the follower node living in it too

### Useful Links

1. follower mode [python script in indexer](https://github.com/algorand/indexer/blob/develop/e2e_tests/src/e2e_conduit/fixtures/importers/follower_algod.py#L91)
2. swap in the network template in this [go-algorand PR](https://github.com/algorand/go-algorand/pull/5157)

**Comment by winder** [comment]
Here is a proof of concept setting up the entire stack with off the shelf docker images:

https://gist.github.com/winder/3b0e3a6464da9a6d9d84bde6b4c35076

**Comment by algoanne** [comment]
we currently have a Docker container for algod and conduit. 
we still need a Docker container for indexer - prerequisite to this issue. 

once we have that, then this ticket will create a docker-compose file that puts it all together for sandbox.

**Comment by algoanne** [comment]
requires design.

**Comment by winder** [comment]
Closing in favor of #182
